"""Initial migration

Revision ID: 921f7e75d42d
Revises: 
Create Date: 2023-06-08 19:19:19.756946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '921f7e75d42d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bidderCode', sa.String(length=50), nullable=True),
    sa.Column('auctionId', sa.String(length=50), nullable=True),
    sa.Column('bidderRequestId', sa.String(length=50), nullable=True),
    sa.Column('bidData', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event')
    # ### end Alembic commands ###
